### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by Butonix** [54sword/xiaoduyu.com#37]
I'm sorry, tell me! Registration only by phone, not email?

**Comment by 54sword** [comment]
we need comply with 《互联网跟帖评论服务管理规定》。
phone in china is Real-name system。

**Comment by Butonix** [comment]
that is, if I'm not from China, I can not register?
can not I remove the phone and put an email for registration?

**Comment by 54sword** [comment]
you can use GitHub sign in.
or in register, you can select your country phone area code.
phone is not support remove, but can change other phone.

**Comment by Butonix** [comment]
Ok
How add category theme?

**Comment by 54sword** [comment]
Quetions 1
1、Set up admin user, in mongodb set user role = 100
2、Sign in admin user, open http://localhost:3000/me url，have "管理社群"、"添加新的社区" features
3、In the future admin.xiaoduyu.com will have more management features

Quetions 2
yes, pictures and static file will upload to CDN(qiniu).

**Comment by Butonix** [comment]
Question 1
And as you then on the server pictures are stored on your server?
https://img.xiaoduyu.com/a5ae5478-0f38-4b16-b1b9-6e6c2c42df79.png?imageMogr2/crop/!676x676a37a54/thumbnail/!50/quality/90
Question 2
can I add an email to the registration
and add the download to your server
I am ready to donate funds to the development of the project

**Comment by 54sword** [comment]
**reply question 1** 
not, pictures is upload to CDN, then CDN can config self domain.

// my domain
https://img.xiaoduyu.com/a5ae5478-0f38-4b16-b1b9-6e6c2c42df79.png?imageMogr2/crop/!676x676a37a54/thumbnail/!50/quality/90

// CDN domain
https://oiy8zs2t8.qnssl.com/a5ae5478-0f38-4b16-b1b9-6e6c2c42df79.png?imageMogr2/crop/!676x676a37a54/thumbnail/!50/quality/90

**reply question 2**
that need change code. 
you can use my code in your project,
but the process is complicated. 
i don't know how to use english expression.

**Comment by Butonix** [comment]
You do not plan to update all the packages to more recent ones?
change es2015 to env
now already webpack 3.10.0
react 16
and so on

**Comment by 54sword** [comment]
yes, i will update it.
because react-router 4 are change too much. no time to refactor yet.

but i has been in admin.xiaoduyu.com use 

- webpack 3
- react 16
- react-router 4
- react-redux
- css modules
- babel-polyfill
- service worker
- i18n (uncertain)

**support**
1、server render (SEO)
2、ragmented by page (page load js on demand)

---

https://github.com/lenage/react-qiniu is old. 
in new react have error, need modify its source code

import PropTypes from 'prop-types'
React.PropTypes change to PropTypes

**Comment by Butonix** [comment]
Look error
react-route 4
TypeError: (0 , _reactRouter.match) is not a function
at start (B:/OSPanel/domains/domain.dev/frontend/server/routes/serverRender.js:84:5)

**Comment by 54sword** [comment]
react-router 4, current not support yet. 
need to rewrite the code.

**Comment by Butonix** [comment]
I'm sorry,why this error in the console constantly?
http://domain.dev/socket.io/?EIO=3&transport=polling&t=M4pmk06

**Comment by 54sword** [comment]
this is a web socket. contact to api.xiaoduyu.com.
in www.xiaoduyu.com, i use nginx proxy www.xiaoduyu.com/socket.io/ to api.xiaoduyu.com.
in localhost not have proxy, so have the error

**Comment by Butonix** [comment]
I'm sorry,one more question!
How to make the counter of views updated automatically, without reloading the page?
2 浏览

**Comment by 54sword** [comment]
posts data is stored in redux.
then use redux dispatch function to update posts.view_count data, it will automatically update view data.

https://redux.js.org/docs/basics/UsageWithReact.html

**Comment by Butonix** [comment]
Hi
Look error console (Github auth)
B:\OSPanel\domains\pjournal.dev\backend\node_modules\qiniu\qiniu\zone.js:24
    var bucket = scope.toString().split(":")[0];
                       ^

TypeError: Cannot read property 'toString' of undefined
    at Object.exports.up_host (B:\OSPanel\domains\pjournal.dev\backend\node_modules\qiniu\qiniu\zone.js:24:24)
    at putReadable (B:\OSPanel\domains\pjournal.dev\backend\node_modules\qiniu\qiniu\io.js:55:8)
    at Object.putFile (B:\OSPanel\domains\pjournal.dev\backend\node_modules\qiniu\qiniu\io.js:120:10)
    at uploadFile (B:/OSPanel/domains/pjournal.dev/backend/app/api/v1/qiniu.js:55:16)
    at B:/OSPanel/domains/pjournal.dev/backend/app/api/v1/qiniu.js:59:5
    at WriteStream.<anonymous> (B:/OSPanel/domains/pjournal.dev/backend/app/common/tools.js:174:7)
    at emitNone (events.js:111:20)
    at WriteStream.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:604:14)
    at afterWrite (_stream_writable.js:455:3)
    at onwrite (_stream_writable.js:445:7)
    at fs.js:2180:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:685:5)

**Comment by 54sword** [comment]
this issues, please submit here
https://github.com/qiniu/nodejs-sdk/issues

**Comment by 54sword** [comment]
Current has been used this way.
When the scroll bar to the bottom of the page, it will trigger the next page to load data.

**Comment by Butonix** [comment]
yes, but if you download the site from scratch and see its code, it displays all the pages at once

**Comment by 54sword** [comment]
yes.
maybe after that will add flip pages.
