### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by ygh1** [54sword/xiaoduyu.com#53]
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/yanguanghao/workspace/xiaoduyu.com-master/node_modules/v8-profiler-node8/build/profiler/v6.1.1/node-v57-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/yanguanghao/workspace/xiaoduyu.com-master/node_modules/v8-profiler-node8/build/profiler/v6.1.1/node-v57-darwin-x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd /Users/yanguanghao/workspace/xiaoduyu.com-master/node_modules/v8-profiler-node8
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/yanguanghao/workspace/xiaoduyu.com-master/node_modules/v8-profiler-node8/build/profiler/v6.1.1/node-v57-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/yanguanghao/workspace/xiaoduyu.com-master/node_modules/v8-profiler-node8/build/profiler/v6.1.1/node-v57-darwin-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/yanguanghao/workspace/xiaoduyu.com-master/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/yanguanghao/workspace/xiaoduyu.com-master/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/yanguanghao/workspace/xiaoduyu.com-master/node_modules/v8-profiler-node8
node-pre-gyp ERR! node -v v8.11.2
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/yanguanghao/workspace/xiaoduyu.com-master/node_modules/v8-profiler-node8/build/profiler/v6.1.1/node-v57-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/yanguanghao/workspace/xiaoduyu.com-master/node_modules/v8-profiler-node8/build/profiler/v6.1.1/node-v57-darwin-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN xiaoduyu.com@2.7.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@6.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler-node8@6.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by WeijiaNing** [comment]
ye i have meet it error

**Comment by 13811787801** [comment]
i meet that erro too! how can i do?
local env is npm version : 7.0.15
when i excute 'npm install' commond ,it will be interrupt,and the erro is :
[root@VM-16-9-centos xiaoduyu.com-master]# npm install
npm ERR! code 1
npm ERR! path /home/xiaoduyu.com-master/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory `/home/xiaoduyu.com-master/node_modules/node-sass/build'
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/ast.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/ast_fwd_decl.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/backtrace.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/base64vlq.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/bind.o
npm ERR!   CC(target) Release/obj.target/libsass/src/libsass/src/cencode.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/check_nesting.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/color_maps.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/constants.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/context.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/cssize.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/emitter.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/environment.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/error_handling.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/eval.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/expand.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/extend.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/file.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/functions.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/inspect.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/json.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/lexer.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/listize.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/memory/SharedPtr.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/node.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/operators.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/output.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/parser.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/plugins.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/position.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/prelexer.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/remove_placeholders.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/sass.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/sass2scss.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/sass_context.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/sass_functions.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/sass_util.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/sass_values.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/source_map.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/subset_map.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/to_c.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/to_value.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/units.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/utf8_string.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/util.o
npm ERR!   CXX(target) Release/obj.target/libsass/src/libsass/src/values.o
npm ERR!   AR(target) Release/obj.target/src/sass.a
npm ERR!   COPY Release/sass.a
npm ERR!   CXX(target) Release/obj.target/binding/src/binding.o
npm ERR! make: Leaving directory `/home/xiaoduyu.com-master/node_modules/node-sass/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@15.4.0 | linux | x64
npm ERR! gyp info spawn /usr/bin/python2
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/xiaoduyu.com-master/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/xiaoduyu.com-master/node_modules/node-sass/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/xiaoduyu.com-master/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.node-gyp/15.4.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/15.4.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/xiaoduyu.com-master/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/15.4.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/xiaoduyu.com-master/node_modules/node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from /root/.node-gyp/15.4.0/include/node/node.h:63:0,
npm ERR!                  from ../../nan/nan.h:54,
npm ERR!                  from ../src/binding.cpp:1:
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h: In member function ‘void v8::TracedReferenceBase<T>::SetSlotThreadSafe(T*)’:
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:912:22: error: expected type-specifier
npm ERR!      reinterpret_cast<std::atomic<T*>*>(&val_)->store(new_val,
npm ERR!                       ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:912:22: error: expected ‘>’
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:912:22: error: expected ‘(’
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:912:22: error: ‘atomic’ is not a member of ‘std’
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:912:35: error: expected primary-expression before ‘*’ token
npm ERR!      reinterpret_cast<std::atomic<T*>*>(&val_)->store(new_val,
npm ERR!                                    ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:912:36: error: expected primary-expression before ‘>’ token
npm ERR!      reinterpret_cast<std::atomic<T*>*>(&val_)->store(new_val,
npm ERR!                                     ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:912:38: error: expected primary-expression before ‘>’ token
npm ERR!      reinterpret_cast<std::atomic<T*>*>(&val_)->store(new_val,
npm ERR!                                       ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:913:54: error: ‘memory_order_relaxed’ is not a member of ‘std’
npm ERR!                                                       std::memory_order_relaxed);
npm ERR!                                                       ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:913:80: error: expected ‘)’ before ‘;’ token
npm ERR!                                                       std::memory_order_relaxed);
npm ERR!                                                                                 ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h: In member function ‘const T* v8::TracedReferenceBase<T>::GetSlotThreadSafe() const’:
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:920:29: error: expected type-specifier
npm ERR!      return reinterpret_cast<std::atomic<const T*> const*>(&val_)->load(
npm ERR!                              ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:920:29: error: expected ‘>’
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:920:29: error: expected ‘(’
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:920:29: error: ‘atomic’ is not a member of ‘std’
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:920:41: error: expected primary-expression before ‘const’
npm ERR!      return reinterpret_cast<std::atomic<const T*> const*>(&val_)->load(
npm ERR!                                          ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:920:41: error: expected ‘)’ before ‘const’
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:920:41: error: expected ‘;’ before ‘const’
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:920:49: error: expected unqualified-id before ‘>’ token
npm ERR!      return reinterpret_cast<std::atomic<const T*> const*>(&val_)->load(
npm ERR!                                                  ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:920:49: error: expected initializer before ‘>’ token
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h: At global scope:
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:1631:58: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!                                  Local<Value> export_value);
npm ERR!                                                           ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:3405:23: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    Local<Value> Name() const { return Description(); }
npm ERR!                        ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:5223:76: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!        ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
npm ERR!                                                                             ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:5270:21: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    bool IsExternal() const;
npm ERR!                      ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:5297:24: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    Contents Externalize();
npm ERR!                         ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:5307:70: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    void Externalize(const std::shared_ptr<BackingStore>& backing_store);
npm ERR!                                                                       ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:5318:24: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    Contents GetContents();
npm ERR!                         ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:5706:76: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!        ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
npm ERR!                                                                             ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:5755:76: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!        ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
npm ERR!                                                                             ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:5764:21: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    bool IsExternal() const;
npm ERR!                      ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:5780:24: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    Contents Externalize();
npm ERR!                         ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:5790:70: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    void Externalize(const std::shared_ptr<BackingStore>& backing_store);
npm ERR!                                                                       ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:5805:24: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    Contents GetContents();
npm ERR!                         ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:7150:28: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    size_t code_range_size() const { return code_range_size_ / kMB; }
npm ERR!                             ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:7152:46: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    void set_code_range_size(size_t limit_in_mb) {
npm ERR!                                               ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:7156:38: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    size_t max_semi_space_size_in_kb() const;
npm ERR!                                       ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:7158:56: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    void set_max_semi_space_size_in_kb(size_t limit_in_kb);
npm ERR!                                                         ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:7160:31: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    size_t max_old_space_size() const { return max_old_generation_size_ / kMB; }
npm ERR!                                ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:7162:49: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    void set_max_old_space_size(size_t limit_in_mb) {
npm ERR!                                                  ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:7166:31: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    size_t max_zone_pool_size() const { return max_zone_pool_size_; }
npm ERR!                                ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:7168:43: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    void set_max_zone_pool_size(size_t bytes) { max_zone_pool_size_ = bytes; }
npm ERR!                                            ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:8758:59: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!                                      MeasureMemoryMode mode);
npm ERR!                                                            ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:8821:36: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    Local<Context> GetEnteredContext();
npm ERR!                                     ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:9105:22: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    void RunMicrotasks() { PerformMicrotaskCheckpoint(); }
npm ERR!                       ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:9149:75: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    void AddMicrotasksCompletedCallback(MicrotasksCompletedCallback callback);
npm ERR!                                                                            ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:9157:78: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    void RemoveMicrotasksCompletedCallback(MicrotasksCompletedCallback callback);
npm ERR!                                                                               ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:9341:30: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    UnwindState GetUnwindState();
npm ERR!                               ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:9404:54: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!        AllowCodeGenerationFromStringsCallback callback);
npm ERR!                                                       ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:9764:75: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    static bool TryHandleSignal(int signal_number, void* info, void* context);
npm ERR!                                                                            ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:10720:55: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!                                  const void* stack_base);
npm ERR!                                                        ^
npm ERR! /root/.node-gyp/15.4.0/include/node/v8.h:10746:65: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    static bool PCIsInV8(const UnwindState& unwind_state, void* pc);
npm ERR!                                                                  ^
npm ERR! In file included from ../../nan/nan.h:54:0,
npm ERR!                  from ../src/binding.cpp:1:
npm ERR! /root/.node-gyp/15.4.0/include/node/node.h: In lambda function:
npm ERR! /root/.node-gyp/15.4.0/include/node/node.h:610:43: error: parameter packs not expanded with ‘...’:
npm ERR!              std::forward<EnvironmentArgs>(env_args)...);
npm ERR!                                            ^
npm ERR! /root/.node-gyp/15.4.0/include/node/node.h:610:43: note:         ‘env_args’
npm ERR! make: *** [Release/obj.target/binding/src/binding.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/xiaoduyu.com-master/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:284:12)
npm ERR! gyp ERR! System Linux 3.10.0-1062.18.1.el7.x86_64
npm ERR! gyp ERR! command "/usr/local/node/node-v15.4.0-linux-x64/bin/node" "/home/xiaoduyu.com-master/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/xiaoduyu.com-master/node_modules/node-sass
npm ERR! gyp ERR! node -v v15.4.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-22T01_46_38_460Z-debug.log

**Comment by leondelee** [comment]
我也有同样的错误

**Comment by leondelee** [comment]
谁能解决下吗，node v16.13.1
